### ISSUE TITLE
npm run setup fails on better-sqlite3

### ISSUE THREAD

**Issue by egcampbell** [epicweb-dev/testing-web-apps#11]
When I run npm run setup I get this error:

> setup
> node ./setup.mjs

▶️  Starting workshop setup...
      Running the following command: npx "https://gist.github.com/kentcdodds/bb452ffe53a5caa3600197e1d8005733" -q
    ▶️  Starting: System Validation
          Ensuring the correct versions of tools are installed on this computer.
          Running the following command: npx "https://gist.github.com/kentcdodds/abbc32701f78fa70298d444c2303b6d9"
    ✅  Success: System Validation

    ▶️  Starting: Dependency Installation
          Installing third party code dependencies so the workshop works properly on this computer.
          Running the following command: npm install --legacy-peer-deps --no-save
npm ERR! code 1
npm ERR! path /Users/to239/Desktop/testing-web-apps/node_modules/better-sqlite3
npm ERR! command failed
npm ERR! command sh -c prebuild-install || node-gyp rebuild --release
npm ERR! prebuild-install warn install No prebuilt binaries found (target=18.16.0 runtime=node arch=arm64 libc= platform=darwin)
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.1
npm ERR! gyp info using node@18.16.0 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.9.6 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
npm ERR! gyp http GET https://nodejs.org/download/release/v18.16.0/node-v18.16.0-headers.tar.gz
npm ERR! gyp WARN install got an error, rolling back install
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack FetchError: request to https://nodejs.org/download/release/v18.16.0/node-v18.16.0-headers.tar.gz failed, reason: unable to get local issuer certificate
npm ERR! gyp ERR! stack     at ClientRequest.<anonymous> (/Users/to239/.nvm/versions/node/v18.16.0/lib/node_modules/npm/node_modules/node-gyp/node_modules/minipass-fetch/lib/index.js:130:14)
npm ERR! gyp ERR! stack     at ClientRequest.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at TLSSocket.socketErrorListener (node:_http_client:502:9)
npm ERR! gyp ERR! stack     at TLSSocket.emit (node:events:525:35)
npm ERR! gyp ERR! stack     at emitErrorNT (node:internal/streams/destroy:151:8)
npm ERR! gyp ERR! stack     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
npm ERR! gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
npm ERR! gyp ERR! System Darwin 22.4.0
npm ERR! gyp ERR! command "/Users/to239/.nvm/versions/node/v18.16.0/bin/node" "/Users/to239/.nvm/versions/node/v18.16.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
npm ERR! gyp ERR! cwd /Users/to239/Desktop/testing-web-apps/node_modules/better-sqlite3
npm ERR! gyp ERR! node -v v18.16.0
npm ERR! gyp ERR! node-gyp -v v9.3.1
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/to239/.npm/_logs/2023-05-09T13_22_59_065Z-debug-0.log

**Comment by kentcdodds** [comment]
I asked Chat GPT and it has a couple of useful suggestions:

---

The error message suggests that there's an issue with the `better-sqlite3` package. The installation process is trying to download prebuilt binaries, but it's not finding any that match your system configuration (node version 18.16.0, arm64 architecture, darwin platform). When it fails to find prebuilt binaries, it attempts to build them from source, but this is where it encounters a problem.

The error `FetchError: request to https://nodejs.org/download/release/v18.16.0/node-v18.16.0-headers.tar.gz failed, reason: unable to get local issuer certificate` suggests that it's not able to download the necessary headers from the Node.js website because of an SSL/TLS certificate problem.

Here are some suggestions to resolve this issue:

1. **Install or update Python**: Node-gyp, which is used to compile the binary, requires Python. From the logs, it seems you have Python 3.9.6, but you might want to check if it's correctly installed and updated.

2. **Network issues**: Check if there's a network problem that's preventing node-gyp from accessing the necessary files. The SSL/TLS error could be caused by a misconfigured proxy, firewall, or similar.

3. **Node.js version**: Try using a different version of Node.js. It's possible that `better-sqlite3` doesn't support Node.js 18.16.0. You can use the Node Version Manager (NVM) to switch between Node.js versions easily.

4. **Install better-sqlite3 directly**: Try installing `better-sqlite3` directly using `npm install better-sqlite3` and see if that works. 

5. **Ignore SSL for npm**: As a last resort, you can configure npm to ignore SSL for the current session. Be aware that this can have security implications, so it should be used carefully and as a last resort:

   ```
   npm set strict-ssl false
   ```

   Remember to set it back to true (`npm set strict-ssl true`) once you're done.

Please let me know if you need further help!

---

**Comment by kentcdodds** [comment]
After looking into this further, I've discovered the reason the installation process requires you to build it with node-gyp is because better-sqlite3 doesn't publish a built version of better-sqlite3 that works on your MacBook to GitHub in their GitHub action which is a part of their release process. And the reason they don't is because GitHub actions don't yet support the arm64 architecture.

This is the same for me (I'm on an M1 chip). However, building it myself hasn't been a problem for me. I believe the primary issue is the certificate as ChatGPT says. Could it be that you're running under a VPN that's causing issues? If so, try turning that off.

**Comment by egcampbell** [comment]
The certificates needed to be set for npm for my machine.  Once I properly set my certificates, the install finished successfully.
